export const UPDATE_SOCKET_STATUS         = 'UPDATE_SOCKET_STATUS';
export const UPDATE_TUNNEL_STATUS         = 'UPDATE_TUNNEL_STATUS';
export const UPDATE_MODEL_ROTATION_VECTOR = 'UPDATE_MODEL_ROTATION_VECTOR';
export const UPDATE_TARGET_RESOLUTION     = 'UPDATE_TARGET_RESOLUTION';
